# Personal information
title: Emilio Martin Lundgaard Lopez
email: emilio@lundgaardlopez.com
twitter_username: emilioidk
github_username:  emilioidk
repository: emilioidk/emilioidk.github.io

# Page information
description: >
  I am a Computer Scientist from Argentina currently living in Aalborg, Denmark.
baseurl: ""
url: "http://localhost:4000"
timezone: Europe/Copenhagen
gems: ['jekyll-github-metadata']

# Exclude
exclude:
- .sass-cache
- .vscode
- backup
- bower_components
- node_modules
- .gitignore
- bower.json
- gulpfile.js
- package.json
- CNAME
- Gemfile*
- README.md

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Build settings
incremental: true
markdown: kramdown
