# Personal information
title: Emilio Martin Lundgaard Lopez
email: emilio@lundgaardlopez.com
twitter_username: emilioidk
github_username:  emilioidk
repository: emilioidk/emilioidk.github.io

# Page information
description: > # this means to ignore newlines until "baseurl:"
  I am a Computer Scientist from Argentina currently living in Aalborg, Denmark.
url: "http://emilio.lundgaardlopez.com" # the base hostname & protocol for your site
baseurl: ""
timezone: Europe/Copenhagen
gems: ['jekyll-github-metadata']

# Exclude
exclude:
- .sass-cache
- .vscode
- backup
- bower_components
- node_modules
- .gitignore
- bower.json
- gulpfile.js
- package.json
- CNAME
- Gemfile*
- README.md

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Build settings
incremental: true
markdown: kramdown
